// <auto-generated />
using System.Collections.Generic;
using BackEndForJawla1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackEndForJawla1.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240512072353_NewTry")]
    partial class NewTry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackEndForJawla1.Models.bucketInfo", b =>
                {
                    b.Property<string>("routeID")
                        .HasColumnType("text");

                    b.Property<List<int>>("nodesInBucket")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("numBuckets")
                        .HasColumnType("integer");

                    b.HasKey("routeID");

                    b.ToTable("bucketInfo");
                });

            modelBuilder.Entity("BackEndForJawla1.Models.busRouteStop", b =>
                {
                    b.Property<string>("routeID")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StopID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StopOrder")
                        .HasColumnType("integer");

                    b.HasKey("routeID");

                    b.ToTable("routeStops");
                });

            modelBuilder.Entity("BackEndForJawla1.Models.busStops", b =>
                {
                    b.Property<string>("stopID")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("stopName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("stopID");

                    b.ToTable("busStops");
                });

            modelBuilder.Entity("BackEndForJawla1.Models.routes", b =>
                {
                    b.Property<string>("routeID")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("routeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("routeID");

                    b.ToTable("routes");
                });
#pragma warning restore 612, 618
        }
    }
}
